version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/shop/Dockerfile
    env_file:
      - configs/shop.env
    networks:
      - webnet
    ports:
      - "8000:8000"
    volumes:
      - ./shop/:/usr/app

  warehouse:
    container_name: warehouse
    build:
      context: .
      dockerfile: docker/warehouse/Dockerfile
    env_file:
      - configs/warehouse.env
    networks:
      - warehouse_net
    ports:
      - "8001:8001"
    volumes:
      - ./warehouse/:/usr/app

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet
    expose:
        - 5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev_db'

  db_warehouse:
    container_name: db_warehouse
    image: postgres:latest
    volumes:
      - db-warehouse-data:/var/lib/postgresql/data
    networks:
      - warehouse_net
    expose:
      - 5432
    environment:
      POSTGRES_USER: 'postgres1'
      POSTGRES_PASSWORD: 'postgres1'
      POSTGRES_DB: 'warehouse_db'

  redis:
    container_name: redis
    image: redis:5.0.6-alpine
    restart: on-failure
    networks:
      - webnet
    expose:
      - 6379
    volumes:
      - redis:/var/lib/redis/data

volumes:
  db-data:
  db-warehouse-data:
  redis:
networks:
  webnet:
  warehouse_net: